/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import java.awt.Toolkit;

/**
 *
 * @author medra
 */
public class VtnAP extends javax.swing.JFrame
{

    private boolean desnutricion;
    private boolean sobrepeso;
    private boolean alergias;
    private boolean obesidad;
    private boolean diabetes;
    private char sexo;
    private int vne;
    private char estatus;
    private String vcve;
    private boolean vb;
    private boolean vf;

    /**
     * Creates new form VtnAA
     */
    public VtnAP()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Imagen1ORGlogo.png")));
        initComponents();
        VtnPrincipal.disablepaste(cve);
        VtnPrincipal.disablepaste(nom);
        VtnPrincipal.disablepaste(primerAP);
        VtnPrincipal.disablepaste(segundoAP);
        VtnPrincipal.disablepaste(otras);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        desnutricionbot = new javax.swing.JCheckBox();
        sobrepesobot = new javax.swing.JCheckBox();
        obesidadbot = new javax.swing.JCheckBox();
        diabetesbot = new javax.swing.JCheckBox();
        alergiabot = new javax.swing.JCheckBox();
        cve = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sexocb = new javax.swing.JComboBox();
        nom = new javax.swing.JTextField();
        primerAP = new javax.swing.JTextField();
        segundoAP = new javax.swing.JTextField();
        otras = new javax.swing.JTextField();
        otrasbot = new javax.swing.JCheckBox();
        estatuscb = new javax.swing.JComboBox();
        jButton_Regresar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cancelar1 = new javax.swing.JButton();
        aceptar1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        otrasboton = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        fondo = new javax.swing.JLabel();

        jLabel1.setText("¿Confirma que desea cancelar el registro?");
        jDialog1.getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);
        jDialog1.getContentPane().add(jTextField1, java.awt.BorderLayout.PAGE_END);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de Personal");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Zilla Slab SemiBold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Datos Clinicos del Personal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        desnutricionbot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desnutricionbot.setEnabled(false);
        desnutricionbot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                desnutricionbotActionPerformed(evt);
            }
        });
        desnutricionbot.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                desnutricionbotKeyPressed(evt);
            }
        });
        getContentPane().add(desnutricionbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        sobrepesobot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sobrepesobot.setEnabled(false);
        sobrepesobot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sobrepesobotActionPerformed(evt);
            }
        });
        getContentPane().add(sobrepesobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        obesidadbot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        obesidadbot.setEnabled(false);
        obesidadbot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                obesidadbotActionPerformed(evt);
            }
        });
        getContentPane().add(obesidadbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        diabetesbot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        diabetesbot.setEnabled(false);
        diabetesbot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                diabetesbotActionPerformed(evt);
            }
        });
        getContentPane().add(diabetesbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        alergiabot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        alergiabot.setEnabled(false);
        alergiabot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                alergiabotActionPerformed(evt);
            }
        });
        getContentPane().add(alergiabot, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        cve.setForeground(new java.awt.Color(102, 51, 0));
        cve.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cveActionPerformed(evt);
            }
        });
        cve.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cveKeyTyped(evt);
            }
        });
        getContentPane().add(cve, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 80, -1));

        jLabel2.setFont(new java.awt.Font("Zilla Slab SemiBold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Datos Personales del Personal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        sexocb.setBackground(new java.awt.Color(102, 102, 0));
        sexocb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1) Masculino", "2) Femenino" }));
        sexocb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sexocb.setEnabled(false);
        sexocb.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sexocbActionPerformed(evt);
            }
        });
        sexocb.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                sexocbKeyPressed(evt);
            }
        });
        getContentPane().add(sexocb, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        nom.setForeground(new java.awt.Color(102, 51, 0));
        nom.setEnabled(false);
        nom.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nomKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nomKeyTyped(evt);
            }
        });
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 120, -1));

        primerAP.setForeground(new java.awt.Color(102, 51, 0));
        primerAP.setEnabled(false);
        primerAP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                primerAPActionPerformed(evt);
            }
        });
        primerAP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                primerAPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                primerAPKeyTyped(evt);
            }
        });
        getContentPane().add(primerAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 110, -1));

        segundoAP.setForeground(new java.awt.Color(102, 51, 0));
        segundoAP.setEnabled(false);
        segundoAP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                segundoAPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                segundoAPKeyTyped(evt);
            }
        });
        getContentPane().add(segundoAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 110, -1));

        otras.setForeground(new java.awt.Color(102, 51, 0));
        otras.setEnabled(false);
        otras.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                otrasActionPerformed(evt);
            }
        });
        otras.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                otrasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                otrasKeyTyped(evt);
            }
        });
        getContentPane().add(otras, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 130, -1));

        otrasbot.setEnabled(false);
        otrasbot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                otrasbotActionPerformed(evt);
            }
        });
        getContentPane().add(otrasbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 130, 20));

        estatuscb.setBackground(new java.awt.Color(102, 102, 0));
        estatuscb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1) Base", "2) Temporal", " " }));
        estatuscb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        estatuscb.setEnabled(false);
        estatuscb.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                estatuscbActionPerformed(evt);
            }
        });
        estatuscb.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                estatuscbKeyPressed(evt);
            }
        });
        getContentPane().add(estatuscb, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jButton_Regresar.setBackground(new java.awt.Color(153, 153, 0));
        jButton_Regresar.setFont(new java.awt.Font("Zilla Slab Medium", 1, 14)); // NOI18N
        jButton_Regresar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Regresar.setText("<");
        jButton_Regresar.setToolTipText("Regresar Regresar a Submenú de Personal");
        jButton_Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_Regresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clinic.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen2.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel15.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 51, 0));
        jLabel15.setText("CVE del personal:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, 20));

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("Nombre(s)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 80, 20));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Primer Apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, 20));

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Segundo Apellido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, 20));

        jLabel19.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 51, 0));
        jLabel19.setText("Estatus");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 51, 0));
        jLabel12.setText("Sexo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 51, 0));
        jLabel14.setText("Desnutrición");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 376, -1, 10));

        jLabel20.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 51, 0));
        jLabel20.setText("Sobrepeso");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, 20));

        jLabel21.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 51, 0));
        jLabel21.setText("Alergias");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, 20));

        jLabel22.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 51, 0));
        jLabel22.setText("Obesidad");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, 20));

        jLabel23.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 51, 0));
        jLabel23.setText("Diabetes");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, 20));

        jLabel24.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 51, 0));
        jLabel24.setText("Otras");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, 20));

        cancelar1.setBackground(new java.awt.Color(153, 153, 0));
        cancelar1.setFont(new java.awt.Font("Zilla Slab Medium", 1, 12)); // NOI18N
        cancelar1.setForeground(new java.awt.Color(255, 255, 255));
        cancelar1.setText("Cancelar");
        cancelar1.setToolTipText("Cancelación de Registro");
        cancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancelar1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, -1, 30));

        aceptar1.setBackground(new java.awt.Color(0, 102, 0));
        aceptar1.setFont(new java.awt.Font("Zilla Slab Medium", 1, 12)); // NOI18N
        aceptar1.setForeground(new java.awt.Color(255, 255, 255));
        aceptar1.setText("Aceptar");
        aceptar1.setToolTipText("Guardar Registro");
        aceptar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aceptar1.setEnabled(false);
        aceptar1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptar1ActionPerformed(evt);
            }
        });
        aceptar1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                aceptar1KeyPressed(evt);
            }
        });
        getContentPane().add(aceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 80, 30));

        jLabel25.setBackground(new java.awt.Color(0, 102, 51));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.png"))); // NOI18N
        jLabel25.setText("jLabel5");
        jLabel25.setMaximumSize(new java.awt.Dimension(540, 100));
        jLabel25.setMinimumSize(new java.awt.Dimension(420, 80));
        jLabel25.setPreferredSize(new java.awt.Dimension(540, 100));
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 650, 110));

        jLabel26.setBackground(new java.awt.Color(0, 102, 51));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.png"))); // NOI18N
        jLabel26.setText("jLabel5");
        jLabel26.setMaximumSize(new java.awt.Dimension(540, 100));
        jLabel26.setMinimumSize(new java.awt.Dimension(420, 80));
        jLabel26.setPreferredSize(new java.awt.Dimension(540, 100));
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 650, 40));

        otrasboton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        otrasboton.setEnabled(false);
        otrasboton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                otrasbotonActionPerformed(evt);
            }
        });
        getContentPane().add(otrasboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        jCheckBox1.setText("Cambiar idioma");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanco.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void desnutricionbotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_desnutricionbotActionPerformed
    {//GEN-HEADEREND:event_desnutricionbotActionPerformed
        if (desnutricionbot.isSelected())
        {
            desnutricion = true;
            CtrlInterfaz.habilita(false, sobrepesobot,obesidadbot);
        }
    }//GEN-LAST:event_desnutricionbotActionPerformed

    private void desnutricionbotKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_desnutricionbotKeyPressed
    {//GEN-HEADEREND:event_desnutricionbotKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_desnutricionbotKeyPressed

    private void sobrepesobotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sobrepesobotActionPerformed
    {//GEN-HEADEREND:event_sobrepesobotActionPerformed
        if (sobrepesobot.isSelected())
        {
            sobrepeso = true;
            CtrlInterfaz.habilita(false, desnutricionbot,obesidadbot);
        }
    }//GEN-LAST:event_sobrepesobotActionPerformed

    private void obesidadbotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_obesidadbotActionPerformed
    {//GEN-HEADEREND:event_obesidadbotActionPerformed
        if (obesidadbot.isSelected())
        {
            obesidad = true;
            CtrlInterfaz.habilita(false, sobrepesobot,desnutricionbot);
        }
    }//GEN-LAST:event_obesidadbotActionPerformed

    private void diabetesbotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_diabetesbotActionPerformed
    {//GEN-HEADEREND:event_diabetesbotActionPerformed
        if (diabetesbot.isSelected())
        {
            diabetes = true;
        }
    }//GEN-LAST:event_diabetesbotActionPerformed

    private void alergiabotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_alergiabotActionPerformed
    {//GEN-HEADEREND:event_alergiabotActionPerformed
        if (alergiabot.isSelected())
        {
            alergias = true;
        }
    }//GEN-LAST:event_alergiabotActionPerformed

    private void cveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cveActionPerformed
    {//GEN-HEADEREND:event_cveActionPerformed
        vf = Manipulacion.verifNR(VtnPrincipal.d, 2, cve.getText());
        if (vf == true)
        {
            Mensajes.error(this, "CVE repetido, Ingrese un CVE correcto");
            CtrlInterfaz.limpia(cve, nom);
            CtrlInterfaz.habilita(false, cve, nom);
            CtrlInterfaz.cambia(cve);
        }
    }//GEN-LAST:event_cveActionPerformed

    private void cveKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cveKeyPressed
    {//GEN-HEADEREND:event_cveKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, cve, nom);
    }//GEN-LAST:event_cveKeyPressed

    private void sexocbActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sexocbActionPerformed
    {//GEN-HEADEREND:event_sexocbActionPerformed
        if (sexocb.getSelectedIndex() == 0)
        {
            sexo = 'M';
        } else
        {
            sexo = 'F';
        }
        CtrlInterfaz.habilita(true, estatuscb);
    }//GEN-LAST:event_sexocbActionPerformed

    private void nomKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomKeyPressed
    {//GEN-HEADEREND:event_nomKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, nom, primerAP);
    }//GEN-LAST:event_nomKeyPressed

    private void primerAPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_primerAPActionPerformed
    {//GEN-HEADEREND:event_primerAPActionPerformed

    }//GEN-LAST:event_primerAPActionPerformed

    private void primerAPKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_primerAPKeyPressed
    {//GEN-HEADEREND:event_primerAPKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, primerAP, segundoAP);
    }//GEN-LAST:event_primerAPKeyPressed

    private void segundoAPKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_segundoAPKeyPressed
    {//GEN-HEADEREND:event_segundoAPKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, segundoAP, sexocb);
    }//GEN-LAST:event_segundoAPKeyPressed

    private void otrasbotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_otrasbotActionPerformed
    {//GEN-HEADEREND:event_otrasbotActionPerformed
        if (otrasboton.isSelected())
        {
            CtrlInterfaz.habilita(true, otras);
            CtrlInterfaz.cambia(otras);
        } else
        {
            CtrlInterfaz.habilita(false, otras);
            CtrlInterfaz.cambia(segundoAP);
        }
    }//GEN-LAST:event_otrasbotActionPerformed

    private void otrasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_otrasActionPerformed
    {//GEN-HEADEREND:event_otrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otrasActionPerformed

    private void otrasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrasKeyPressed
    {//GEN-HEADEREND:event_otrasKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, otras, aceptar1);
    }//GEN-LAST:event_otrasKeyPressed

    private void cveKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cveKeyTyped
    {//GEN-HEADEREND:event_cveKeyTyped
        Validaciones.validaEntero(evt, 7, cve.getText());
    }//GEN-LAST:event_cveKeyTyped

    private void nomKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomKeyTyped
    {//GEN-HEADEREND:event_nomKeyTyped
        Validaciones.validaAlfabeticos(evt, 30, nom.getText());
    }//GEN-LAST:event_nomKeyTyped

    private void segundoAPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_segundoAPKeyTyped
    {//GEN-HEADEREND:event_segundoAPKeyTyped
        Validaciones.validaAlfabeticos(evt, 15, segundoAP.getText());
    }//GEN-LAST:event_segundoAPKeyTyped

    private void primerAPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_primerAPKeyTyped
    {//GEN-HEADEREND:event_primerAPKeyTyped
        Validaciones.validaAlfabeticos(evt, 12, primerAP.getText());
    }//GEN-LAST:event_primerAPKeyTyped

    private void otrasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrasKeyTyped
    {//GEN-HEADEREND:event_otrasKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, otras.getText());
    }//GEN-LAST:event_otrasKeyTyped

    private void estatuscbActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_estatuscbActionPerformed
    {//GEN-HEADEREND:event_estatuscbActionPerformed
        if (estatuscb.getSelectedIndex() == 0)
        {
            estatus = 'B';
        } else
        {
            estatus = 'T';
        }
        CtrlInterfaz.habilita(true, aceptar1, desnutricionbot, sobrepesobot, alergiabot, obesidadbot, diabetesbot, otrasboton);
    }//GEN-LAST:event_estatuscbActionPerformed

    private void sexocbKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_sexocbKeyPressed
    {//GEN-HEADEREND:event_sexocbKeyPressed
        Validaciones.enter(this, evt, estatuscb);
        sexo = 'M';
    }//GEN-LAST:event_sexocbKeyPressed

    private void estatuscbKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_estatuscbKeyPressed
    {//GEN-HEADEREND:event_estatuscbKeyPressed
        Validaciones.enter(this, evt, aceptar1);
        estatus = 'B';
        CtrlInterfaz.habilita(true, aceptar1, desnutricionbot, sobrepesobot, alergiabot, obesidadbot, diabetesbot, otrasboton);
    }//GEN-LAST:event_estatuscbKeyPressed

    private void jButton_RegresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_RegresarActionPerformed
    {//GEN-HEADEREND:event_jButton_RegresarActionPerformed
        new VtnSubmenu().setVisible(true);
        VtnSubmenu.tsubmenu.setText("           de Personal");
        dispose();
    }//GEN-LAST:event_jButton_RegresarActionPerformed

    private void cancelar1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelar1ActionPerformed
    {//GEN-HEADEREND:event_cancelar1ActionPerformed

        CtrlInterfaz.limpia(cve, nom, primerAP, segundoAP, sexocb, estatuscb, desnutricion, sobrepeso, alergias, obesidad, diabetes, otras, estatus);
        sexocb.setSelectedIndex(0);
        estatuscb.setSelectedIndex(0);
        CtrlInterfaz.habilita(false, cve, nom, primerAP, segundoAP, sexocb, estatuscb, otras, desnutricionbot, sobrepesobot, alergiabot, obesidadbot, diabetesbot, otrasboton, aceptar1);
        otrasboton.setSelected(false);
        desnutricionbot.setSelected(false);
        sobrepesobot.setSelected(false);
        alergiabot.setSelected(false);
        obesidadbot.setSelected(false);
        diabetesbot.setSelected(false);
        CtrlInterfaz.habilita(false, aceptar1);
        CtrlInterfaz.cambia(cve);
        
        
        
    }//GEN-LAST:event_cancelar1ActionPerformed

    private void aceptar1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptar1ActionPerformed
    {//GEN-HEADEREND:event_aceptar1ActionPerformed
        try
        {
            Personal pcd = new Personal(cve.getText(), nom.getText(), primerAP.getText(), segundoAP.getText(), sexo, desnutricion, sobrepeso, alergias, obesidad, diabetes, otras.getText(), estatus);
            VtnPrincipal.d = Manipulacion.inserta(VtnPrincipal.d, pcd);//Funcion para insertar datos
            VtnPrincipal.h = Manipulacion.insf(VtnPrincipal.h,this);
            ManipulacionArchivos.guardaA(this, VtnPrincipal.d, "Datos.dat");
            ManipulacionArchivos.guarda(this, VtnPrincipal.h, "Historial.dat");
            Mensajes.exito(this, "Datos guardados con éxito");
            CtrlInterfaz.limpia(cve, nom, primerAP, segundoAP, sexocb, estatuscb, desnutricion, sobrepeso, alergias, obesidad, diabetes, otras, estatus);
            sexocb.setSelectedIndex(0);
            estatuscb.setSelectedIndex(0);
            CtrlInterfaz.habilita(false, cve, nom, primerAP, segundoAP, sexocb, estatuscb, otras, desnutricionbot, sobrepesobot, alergiabot, obesidadbot, diabetesbot, otrasboton, aceptar1);
            CtrlInterfaz.cambia(cve);
            otrasboton.setSelected(false);
            desnutricionbot.setSelected(false);
            sobrepesobot.setSelected(false);
            alergiabot.setSelected(false);
            obesidadbot.setSelected(false);
            diabetesbot.setSelected(false);
        } catch (Exception e)
        {
            Mensajes.error(this, "Error: " + e.toString());
        }
    }//GEN-LAST:event_aceptar1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        CtrlInterfaz.cambia(cve);
    }//GEN-LAST:event_formWindowOpened

    private void otrasbotonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_otrasbotonActionPerformed
    {//GEN-HEADEREND:event_otrasbotonActionPerformed
        if (otrasboton.isSelected())
        {
            CtrlInterfaz.habilita(true, otras);
            CtrlInterfaz.cambia(otras);
        } else
        {
            CtrlInterfaz.habilita(false, otras);
            CtrlInterfaz.cambia(estatuscb);
        }
    }//GEN-LAST:event_otrasbotonActionPerformed

    private void aceptar1KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_aceptar1KeyPressed
    {//GEN-HEADEREND:event_aceptar1KeyPressed
         try
        {
            Personal pcd = new Personal(cve.getText(), nom.getText(), primerAP.getText(), segundoAP.getText(), sexo, desnutricion, sobrepeso, alergias, obesidad, diabetes, otras.getText(), estatus);
            VtnPrincipal.d = Manipulacion.inserta(VtnPrincipal.d, pcd);//Funcion para insertar datos
            VtnPrincipal.h = Manipulacion.insf(VtnPrincipal.h,this);
            ManipulacionArchivos.guardaA(this, VtnPrincipal.d, "Datos.dat");
            ManipulacionArchivos.guarda(this, VtnPrincipal.h, "Historial.dat");
            Mensajes.exito(this, "Datos guardados con éxito");
            CtrlInterfaz.limpia(cve, nom, primerAP, segundoAP, sexocb, estatuscb, desnutricion, sobrepeso, alergias, obesidad, diabetes, otras, estatus);
            sexocb.setSelectedIndex(0);
            estatuscb.setSelectedIndex(0);
            CtrlInterfaz.habilita(false, cve, nom, primerAP, segundoAP, sexocb, estatuscb, otras, desnutricionbot, sobrepesobot, alergiabot, obesidadbot, diabetesbot, otrasboton, aceptar1);
            CtrlInterfaz.cambia(cve);
            otrasboton.setSelected(false);
            desnutricionbot.setSelected(false);
            sobrepesobot.setSelected(false);
            alergiabot.setSelected(false);
            obesidadbot.setSelected(false);
            diabetesbot.setSelected(false);
        } catch (Exception e)
        {
            Mensajes.error(this, "Error: " + e.toString());
        }
    }//GEN-LAST:event_aceptar1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InstantiationException
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnAP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar1;
    private javax.swing.JCheckBox alergiabot;
    private javax.swing.JButton cancelar1;
    private javax.swing.JTextField cve;
    private javax.swing.JCheckBox desnutricionbot;
    private javax.swing.JCheckBox diabetesbot;
    private javax.swing.JComboBox estatuscb;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton_Regresar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nom;
    private javax.swing.JCheckBox obesidadbot;
    private javax.swing.JTextField otras;
    private javax.swing.JCheckBox otrasbot;
    private javax.swing.JCheckBox otrasboton;
    private javax.swing.JTextField primerAP;
    private javax.swing.JTextField segundoAP;
    private javax.swing.JComboBox sexocb;
    private javax.swing.JCheckBox sobrepesobot;
    // End of variables declaration//GEN-END:variables

}
