package poo;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author medra
 */
public class VtnAA extends javax.swing.JFrame
{

    private boolean desnutricion;
    private boolean sobrepeso;
    private boolean alergias;
    private boolean obesidad;
    private boolean diabetes;
    private char sexo;
    private int vne = 0;
    private String vcve;
    private boolean vb;
    private int v;
    private boolean vf;

    public static Datos d[];//Arreglo de datos
    public static int opc = 1;
    public static HistorialClinico[][] h;
    private String carrera;

    /**
     * Creates new form VtnAA
     */
    public VtnAA()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Imagen1ORGlogo.png")));
        initComponents();
        this.setLocationRelativeTo(null);

        VtnPrincipal.disablepaste(cve);
        VtnPrincipal.disablepaste(nom);
        VtnPrincipal.disablepaste(primerAP);
        VtnPrincipal.disablepaste(segundoAP);
        VtnPrincipal.disablepaste(otras);
    }

    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Imagenc.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        desnutricionbot = new javax.swing.JCheckBox();
        sobrepesobot = new javax.swing.JCheckBox();
        obesidadbot = new javax.swing.JCheckBox();
        diabetesbot = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        alergiabot = new javax.swing.JCheckBox();
        cve = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sexocb = new javax.swing.JComboBox();
        nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        primerAP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        segundoAP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        otrasboton = new javax.swing.JCheckBox();
        otras = new javax.swing.JTextField();
        otrasbot = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        viveconcb = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jButton_Regresar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        carreracb = new javax.swing.JComboBox();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Zilla Slab SemiBold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Datos Clínicos del Alumno");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("Nombre(s)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 70, 20));

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 0));
        jLabel8.setText("Sobrepeso");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, 20));

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 51, 0));
        jLabel9.setText("Alergias");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, 20));

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 51, 0));
        jLabel10.setText("Obesidad");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, 20));

        jLabel11.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 51, 0));
        jLabel11.setText("Diabetes");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, 20));

        desnutricionbot.setForeground(new java.awt.Color(0, 102, 0));
        desnutricionbot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        desnutricionbot.setEnabled(false);
        desnutricionbot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                desnutricionbotActionPerformed(evt);
            }
        });
        desnutricionbot.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                desnutricionbotKeyPressed(evt);
            }
        });
        getContentPane().add(desnutricionbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        sobrepesobot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sobrepesobot.setEnabled(false);
        sobrepesobot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sobrepesobotActionPerformed(evt);
            }
        });
        getContentPane().add(sobrepesobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, 20));

        obesidadbot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        obesidadbot.setEnabled(false);
        obesidadbot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                obesidadbotActionPerformed(evt);
            }
        });
        getContentPane().add(obesidadbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        diabetesbot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        diabetesbot.setEnabled(false);
        diabetesbot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                diabetesbotActionPerformed(evt);
            }
        });
        getContentPane().add(diabetesbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, 20));

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("CVE del Alumno:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, 20));

        alergiabot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alergiabot.setEnabled(false);
        alergiabot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                alergiabotActionPerformed(evt);
            }
        });
        getContentPane().add(alergiabot, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, 20));

        cve.setForeground(new java.awt.Color(102, 51, 0));
        cve.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cveActionPerformed(evt);
            }
        });
        cve.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cveKeyTyped(evt);
            }
        });
        getContentPane().add(cve, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 90, -1));

        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 51, 0));
        jLabel12.setText("Sexo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Zilla Slab SemiBold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Datos Personales del Alumno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        sexocb.setBackground(new java.awt.Color(102, 102, 0));
        sexocb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1) Masculino", "2) Femenino" }));
        sexocb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sexocb.setEnabled(false);
        sexocb.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sexocbActionPerformed(evt);
            }
        });
        sexocb.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                sexocbKeyPressed(evt);
            }
        });
        getContentPane().add(sexocb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        nom.setForeground(new java.awt.Color(102, 51, 0));
        nom.setEnabled(false);
        nom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nomActionPerformed(evt);
            }
        });
        nom.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nomKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nomKeyTyped(evt);
            }
        });
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 150, -1));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Primer Apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, 20));

        primerAP.setForeground(new java.awt.Color(102, 51, 0));
        primerAP.setEnabled(false);
        primerAP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                primerAPActionPerformed(evt);
            }
        });
        primerAP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                primerAPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                primerAPKeyTyped(evt);
            }
        });
        getContentPane().add(primerAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 110, -1));

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Segundo Apellido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, 20));

        segundoAP.setForeground(new java.awt.Color(102, 51, 0));
        segundoAP.setEnabled(false);
        segundoAP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                segundoAPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                segundoAPKeyTyped(evt);
            }
        });
        getContentPane().add(segundoAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 110, -1));

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Desnutrición");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 376, -1, 10));

        aceptar.setBackground(new java.awt.Color(0, 102, 0));
        aceptar.setFont(new java.awt.Font("Zilla Slab Medium", 1, 12)); // NOI18N
        aceptar.setForeground(new java.awt.Color(255, 255, 255));
        aceptar.setText("Aceptar");
        aceptar.setToolTipText("Guardar Registro");
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.setEnabled(false);
        aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarActionPerformed(evt);
            }
        });
        aceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                aceptarKeyPressed(evt);
            }
        });
        getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 80, 30));

        cancelar.setBackground(new java.awt.Color(153, 153, 0));
        cancelar.setFont(new java.awt.Font("Zilla Slab Medium", 1, 12)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setText("Cancelar");
        cancelar.setToolTipText("Cancelación de Registro");
        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, -1, 30));

        jLabel13.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 51, 0));
        jLabel13.setText("Otras");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, 20));

        otrasboton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        otrasboton.setEnabled(false);
        otrasboton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                otrasbotonActionPerformed(evt);
            }
        });
        getContentPane().add(otrasboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        otras.setForeground(new java.awt.Color(102, 51, 0));
        otras.setEnabled(false);
        otras.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                otrasActionPerformed(evt);
            }
        });
        otras.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                otrasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                otrasKeyTyped(evt);
            }
        });
        getContentPane().add(otras, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 130, -1));

        otrasbot.setEnabled(false);
        otrasbot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                otrasbotActionPerformed(evt);
            }
        });
        getContentPane().add(otrasbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 130, 20));

        jLabel14.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 51, 0));
        jLabel14.setText("Vive con");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        viveconcb.setBackground(new java.awt.Color(102, 102, 0));
        viveconcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1) Mamá y Papa", "2) Solo Mamá", "3) Solo Papá", "4) Otros" }));
        viveconcb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viveconcb.setEnabled(false);
        viveconcb.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                viveconcbActionPerformed(evt);
            }
        });
        viveconcb.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                viveconcbKeyPressed(evt);
            }
        });
        getContentPane().add(viveconcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        jLabel15.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 51, 0));
        jLabel15.setText("Carrera");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        jButton_Regresar.setBackground(new java.awt.Color(153, 153, 0));
        jButton_Regresar.setFont(new java.awt.Font("Zilla Slab Medium", 1, 14)); // NOI18N
        jButton_Regresar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Regresar.setText("<");
        jButton_Regresar.setToolTipText("Regresar a Submenú de Alumnos");
        jButton_Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Regresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen2.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clinic.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        jLabel19.setBackground(new java.awt.Color(0, 102, 51));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.png"))); // NOI18N
        jLabel19.setText("jLabel5");
        jLabel19.setMaximumSize(new java.awt.Dimension(540, 100));
        jLabel19.setMinimumSize(new java.awt.Dimension(420, 80));
        jLabel19.setPreferredSize(new java.awt.Dimension(540, 100));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 650, 40));

        jLabel20.setBackground(new java.awt.Color(0, 102, 51));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.png"))); // NOI18N
        jLabel20.setText("jLabel5");
        jLabel20.setMaximumSize(new java.awt.Dimension(540, 100));
        jLabel20.setMinimumSize(new java.awt.Dimension(420, 80));
        jLabel20.setPreferredSize(new java.awt.Dimension(540, 100));
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 650, 110));

        carreracb.setBackground(new java.awt.Color(102, 102, 0));
        carreracb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1) ISW", "2) ICO", "3) IPP", "4) IPI", "5) IME", "6) LSC" }));
        carreracb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        carreracb.setEnabled(false);
        carreracb.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                carreracbActionPerformed(evt);
            }
        });
        carreracb.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                carreracbKeyPressed(evt);
            }
        });
        getContentPane().add(carreracb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanco.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void desnutricionbotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_desnutricionbotActionPerformed
    {//GEN-HEADEREND:event_desnutricionbotActionPerformed
        if (desnutricionbot.isSelected())
        {
            desnutricion = true;
            CtrlInterfaz.habilita(false, sobrepesobot,obesidadbot);
        }
    }//GEN-LAST:event_desnutricionbotActionPerformed

    private void desnutricionbotKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_desnutricionbotKeyPressed
    {//GEN-HEADEREND:event_desnutricionbotKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_desnutricionbotKeyPressed

    private void sobrepesobotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sobrepesobotActionPerformed
    {//GEN-HEADEREND:event_sobrepesobotActionPerformed
        if (sobrepesobot.isSelected())
        {
            sobrepeso = true;
            CtrlInterfaz.habilita(false, desnutricionbot,obesidadbot);
        }
    }//GEN-LAST:event_sobrepesobotActionPerformed

    private void obesidadbotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_obesidadbotActionPerformed
    {//GEN-HEADEREND:event_obesidadbotActionPerformed
        if (obesidadbot.isSelected())
        {
            obesidad = true;
            CtrlInterfaz.habilita(false, sobrepesobot,desnutricionbot);
        }
    }//GEN-LAST:event_obesidadbotActionPerformed

    private void diabetesbotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_diabetesbotActionPerformed
    {//GEN-HEADEREND:event_diabetesbotActionPerformed
        if (diabetesbot.isSelected())
        {
            diabetes = true;
        }
    }//GEN-LAST:event_diabetesbotActionPerformed

    private void alergiabotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_alergiabotActionPerformed
    {//GEN-HEADEREND:event_alergiabotActionPerformed
        if (alergiabot.isSelected())
        {
            alergias = true;
        }
    }//GEN-LAST:event_alergiabotActionPerformed

    private void cveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cveActionPerformed
    {//GEN-HEADEREND:event_cveActionPerformed
        vf = Manipulacion.verifNR(VtnPrincipal.d, 1, cve.getText());
        if (vf == true)
        {
            Mensajes.error(this, "CVE repetido, Ingrese un CVE correcto");
            CtrlInterfaz.limpia(cve, nom);
            CtrlInterfaz.habilita(false, cve, nom);
            CtrlInterfaz.cambia(cve);
        }
    }//GEN-LAST:event_cveActionPerformed

    private void cveKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cveKeyPressed
    {//GEN-HEADEREND:event_cveKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, cve, nom);
    }//GEN-LAST:event_cveKeyPressed

    private void sexocbActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sexocbActionPerformed
    {//GEN-HEADEREND:event_sexocbActionPerformed
        if (sexocb.getSelectedIndex() == 0)
        {
            sexo = 'M';
        } else
        {
            sexo = 'F';
        }
        CtrlInterfaz.habilita(true, viveconcb);
    }//GEN-LAST:event_sexocbActionPerformed

    private void nomKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomKeyPressed
    {//GEN-HEADEREND:event_nomKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, nom, primerAP);
    }//GEN-LAST:event_nomKeyPressed

    private void primerAPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_primerAPActionPerformed
    {//GEN-HEADEREND:event_primerAPActionPerformed

    }//GEN-LAST:event_primerAPActionPerformed

    private void primerAPKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_primerAPKeyPressed
    {//GEN-HEADEREND:event_primerAPKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, primerAP, segundoAP);
    }//GEN-LAST:event_primerAPKeyPressed

    private void segundoAPKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_segundoAPKeyPressed
    {//GEN-HEADEREND:event_segundoAPKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, segundoAP, carreracb);
    }//GEN-LAST:event_segundoAPKeyPressed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarActionPerformed
    {//GEN-HEADEREND:event_aceptarActionPerformed
        try
        {
            Alumnos pcd = new Alumnos(cve.getText(), nom.getText(), primerAP.getText(), segundoAP.getText(), sexo, desnutricion, sobrepeso, alergias, obesidad, diabetes, otras.getText(), (viveconcb.getSelectedIndex() + 1), carrera);
            VtnPrincipal.d = Manipulacion.inserta(VtnPrincipal.d, pcd);//Funcion para insertar datos
            VtnPrincipal.h = Manipulacion.insf(VtnPrincipal.h, this);
            ManipulacionArchivos.guardaA(this, VtnPrincipal.d, "Datos.dat");
            ManipulacionArchivos.guarda(this, VtnPrincipal.h, "Historial.dat");
            Mensajes.exito(this, "Datos guardados con éxito");
            CtrlInterfaz.limpia(cve, nom, primerAP, segundoAP, sexocb, viveconcb, desnutricion, sobrepeso, alergias, obesidad, diabetes, otras, carrera, carreracb);
            sexocb.setSelectedIndex(0);
            viveconcb.setSelectedIndex(0);
            carreracb.setSelectedIndex(0);
            CtrlInterfaz.habilita(false, cve, nom, primerAP, segundoAP, sexocb, viveconcb, otras, desnutricionbot, sobrepesobot, alergiabot, obesidadbot, diabetesbot, otrasboton, carrera, aceptar, carreracb);
            CtrlInterfaz.cambia(cve);
            otrasboton.setSelected(false);
            desnutricionbot.setSelected(false);
            sobrepesobot.setSelected(false);
            alergiabot.setSelected(false);
            obesidadbot.setSelected(false);
            diabetesbot.setSelected(false);

            VtnRA obj = new VtnRA();
            obj.model.addRow(d);

        } catch (Exception e)
        {
            Mensajes.error(this, "Error: " + e.toString());
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarActionPerformed
    {//GEN-HEADEREND:event_cancelarActionPerformed

        CtrlInterfaz.limpia(cve, nom, primerAP, segundoAP, sexocb, viveconcb, desnutricion, sobrepeso, alergias, obesidad, diabetes, otras, carrera, carreracb);
        sexocb.setSelectedIndex(0);
        viveconcb.setSelectedIndex(0);
        carreracb.setSelectedIndex(0);
        CtrlInterfaz.habilita(false, cve, nom, primerAP, segundoAP, sexocb, viveconcb, otras, desnutricionbot, sobrepesobot, alergiabot, obesidadbot, diabetesbot, otrasboton, carrera, aceptar, carreracb);
        CtrlInterfaz.cambia(cve);
        otrasboton.setSelected(false);
        desnutricionbot.setSelected(false);
        sobrepesobot.setSelected(false);
        alergiabot.setSelected(false);
        obesidadbot.setSelected(false);
        diabetesbot.setSelected(false);
        CtrlInterfaz.habilita(false, aceptar);
        CtrlInterfaz.cambia(cve);
    }//GEN-LAST:event_cancelarActionPerformed

    private void otrasbotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_otrasbotActionPerformed
    {//GEN-HEADEREND:event_otrasbotActionPerformed
        if (otrasboton.isSelected())
        {
            CtrlInterfaz.habilita(true, otras);
            CtrlInterfaz.cambia(otras);
        } else
        {
            CtrlInterfaz.habilita(false, otras);
            CtrlInterfaz.cambia(carrera);
        }
    }//GEN-LAST:event_otrasbotActionPerformed

    private void otrasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_otrasActionPerformed
    {//GEN-HEADEREND:event_otrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otrasActionPerformed

    private void otrasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrasKeyPressed
    {//GEN-HEADEREND:event_otrasKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, otras, aceptar);
    }//GEN-LAST:event_otrasKeyPressed

    private void cveKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cveKeyTyped
    {//GEN-HEADEREND:event_cveKeyTyped
        Validaciones.validaEntero(evt, 7, cve.getText());
    }//GEN-LAST:event_cveKeyTyped

    private void nomKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomKeyTyped
    {//GEN-HEADEREND:event_nomKeyTyped
        Validaciones.validaAlfabeticos(evt, 30, nom.getText());
    }//GEN-LAST:event_nomKeyTyped

    private void segundoAPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_segundoAPKeyTyped
    {//GEN-HEADEREND:event_segundoAPKeyTyped
        Validaciones.validaAlfabeticos(evt, 15, segundoAP.getText());
    }//GEN-LAST:event_segundoAPKeyTyped

    private void primerAPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_primerAPKeyTyped
    {//GEN-HEADEREND:event_primerAPKeyTyped
        Validaciones.validaAlfabeticos(evt, 12, primerAP.getText());
    }//GEN-LAST:event_primerAPKeyTyped

    private void otrasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrasKeyTyped
    {//GEN-HEADEREND:event_otrasKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, otras.getText());
    }//GEN-LAST:event_otrasKeyTyped

    private void viveconcbActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_viveconcbActionPerformed
    {//GEN-HEADEREND:event_viveconcbActionPerformed
        CtrlInterfaz.habilita(true, aceptar, desnutricionbot, sobrepesobot, alergiabot, obesidadbot, diabetesbot, otrasboton);
    }//GEN-LAST:event_viveconcbActionPerformed

    private void sexocbKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_sexocbKeyPressed
    {//GEN-HEADEREND:event_sexocbKeyPressed
        Validaciones.enter(this, evt, viveconcb);
        sexo = 'M';
    }//GEN-LAST:event_sexocbKeyPressed

    private void viveconcbKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_viveconcbKeyPressed
    {//GEN-HEADEREND:event_viveconcbKeyPressed
        CtrlInterfaz.habilita(true, aceptar, desnutricionbot, sobrepesobot, alergiabot, obesidadbot, diabetesbot, otrasboton);
        Validaciones.enter(this, evt, aceptar);
        viveconcb.setSelectedIndex(0);
    }//GEN-LAST:event_viveconcbKeyPressed

    private void nomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nomActionPerformed
    {//GEN-HEADEREND:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void jButton_RegresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_RegresarActionPerformed
    {//GEN-HEADEREND:event_jButton_RegresarActionPerformed
        new VtnSubmenu().setVisible(true);
        VtnSubmenu.tsubmenu.setText("           de Alumnos");
        dispose();
    }//GEN-LAST:event_jButton_RegresarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        CtrlInterfaz.cambia(cve);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        ManipulacionArchivos.guardaA(this, d, "Datos.dat");
        ManipulacionArchivos.guarda(this, h, "Historial.dat");
    }//GEN-LAST:event_formWindowClosing

    private void otrasbotonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_otrasbotonActionPerformed
    {//GEN-HEADEREND:event_otrasbotonActionPerformed
        if (otrasboton.isSelected())
        {
            CtrlInterfaz.habilita(true, otras);
            CtrlInterfaz.cambia(otras);
        } else
        {
            CtrlInterfaz.habilita(false, otras);
            CtrlInterfaz.cambia(carrera);
        }
    }//GEN-LAST:event_otrasbotonActionPerformed

    private void carreracbActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_carreracbActionPerformed
    {//GEN-HEADEREND:event_carreracbActionPerformed
        if (carreracb.getSelectedIndex() == 0)
        {
            carrera = "ISW";
        }
        if (carreracb.getSelectedIndex() == 1)
        {
            carrera = "ICO";
        }
        if (carreracb.getSelectedIndex() == 2)
        {
            carrera = "IPP";
        }
        if (carreracb.getSelectedIndex() == 3)
        {
            carrera = "IPI";
        }
        if (carreracb.getSelectedIndex() == 4)
        {
            carrera = "IME";
        }
        if (carreracb.getSelectedIndex() == 5)
        {
            carrera = "LSC";
        }
        CtrlInterfaz.habilita(true, sexocb);
    }//GEN-LAST:event_carreracbActionPerformed

    private void carreracbKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_carreracbKeyPressed
    {//GEN-HEADEREND:event_carreracbKeyPressed
        Validaciones.enter(this, evt, sexocb);
        carrera = "ISW";
    }//GEN-LAST:event_carreracbKeyPressed

    private void aceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_aceptarKeyPressed
    {//GEN-HEADEREND:event_aceptarKeyPressed
        try
        {
            Alumnos pcd = new Alumnos(cve.getText(), nom.getText(), primerAP.getText(), segundoAP.getText(), sexo, desnutricion, sobrepeso, alergias, obesidad, diabetes, otras.getText(), (viveconcb.getSelectedIndex() + 1), carrera);
            VtnPrincipal.d = Manipulacion.inserta(VtnPrincipal.d, pcd);//Funcion para insertar datos
            VtnPrincipal.h = Manipulacion.insf(VtnPrincipal.h, this);
            ManipulacionArchivos.guardaA(this, VtnPrincipal.d, "Datos.dat");
            ManipulacionArchivos.guarda(this, VtnPrincipal.h, "Historial.dat");
            Mensajes.exito(this, "Datos guardados con éxito");
            CtrlInterfaz.limpia(cve, nom, primerAP, segundoAP, sexocb, viveconcb, desnutricion, sobrepeso, alergias, obesidad, diabetes, otras, carrera, carreracb);
            sexocb.setSelectedIndex(0);
            viveconcb.setSelectedIndex(0);
            carreracb.setSelectedIndex(0);
            CtrlInterfaz.habilita(false, cve, nom, primerAP, segundoAP, sexocb, viveconcb, otras, desnutricionbot, sobrepesobot, alergiabot, obesidadbot, diabetesbot, otrasboton, carrera, aceptar, carreracb);
            CtrlInterfaz.cambia(cve);
            otrasboton.setSelected(false);
            desnutricionbot.setSelected(false);
            sobrepesobot.setSelected(false);
            alergiabot.setSelected(false);
            obesidadbot.setSelected(false);
            diabetesbot.setSelected(false);

            VtnRA obj = new VtnRA();
            obj.model.addRow(d);

        } catch (Exception e)
        {
            Mensajes.error(this, "Error: " + e.toString());
        }
    }//GEN-LAST:event_aceptarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnAA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnAA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnAA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnAA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnAA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JCheckBox alergiabot;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox carreracb;
    private javax.swing.JTextField cve;
    private javax.swing.JCheckBox desnutricionbot;
    private javax.swing.JCheckBox diabetesbot;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton_Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nom;
    private javax.swing.JCheckBox obesidadbot;
    private javax.swing.JTextField otras;
    private javax.swing.JCheckBox otrasbot;
    private javax.swing.JCheckBox otrasboton;
    private javax.swing.JTextField primerAP;
    private javax.swing.JTextField segundoAP;
    private javax.swing.JComboBox sexocb;
    private javax.swing.JCheckBox sobrepesobot;
    private javax.swing.JComboBox viveconcb;
    // End of variables declaration//GEN-END:variables
}
