/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author medra
 */
public class VtnHCA extends javax.swing.JFrame
{

    private int vne;
    private LocalDate fecha;
    private GregorianCalendar c;

    /**
     * Creates new form VtnHC
     */
    public VtnHCA()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Imagen1ORGlogo.png")));
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane4 = new javax.swing.JScrollPane();
        medic = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        antece = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        planTrat = new javax.swing.JTextArea();
        fechas = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        cve = new javax.swing.JTextField();
        pada = new javax.swing.JScrollPane();
        padAct = new javax.swing.JTextArea();
        Cancelar = new javax.swing.JButton();
        jButton_Regresar2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso de Consulta Alumno");
        setBackground(new java.awt.Color(0, 153, 255));
        setName("Registro de Consulta"); // NOI18N
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medic.setColumns(20);
        medic.setForeground(new java.awt.Color(102, 51, 0));
        medic.setRows(5);
        medic.setTabSize(6);
        medic.setCaretColor(new java.awt.Color(0, 51, 102));
        medic.setEnabled(false);
        medic.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                medicKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                medicKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(medic);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 380, 250, 110));

        antece.setColumns(20);
        antece.setForeground(new java.awt.Color(102, 51, 0));
        antece.setRows(5);
        antece.setTabSize(6);
        antece.setCaretColor(new java.awt.Color(0, 51, 102));
        antece.setEnabled(false);
        antece.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                anteceKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                anteceKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(antece);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 200, 250, 110));

        planTrat.setColumns(20);
        planTrat.setForeground(new java.awt.Color(102, 51, 0));
        planTrat.setRows(5);
        planTrat.setTabSize(6);
        planTrat.setCaretColor(new java.awt.Color(0, 51, 102));
        planTrat.setEnabled(false);
        planTrat.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                planTratKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                planTratKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(planTrat);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 240, 110));

        fechas.setCaretColor(new java.awt.Color(0, 0, 102));
        fechas.setDisabledTextColor(new java.awt.Color(102, 51, 0));
        fechas.setEnabled(false);
        fechas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fechaActionPerformed(evt);
            }
        });
        fechas.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                fechasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                fechaKeyTyped(evt);
            }
        });
        getContentPane().add(fechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 100, -1));

        Aceptar.setBackground(new java.awt.Color(0, 102, 0));
        Aceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar.setText("Aceptar");
        Aceptar.setToolTipText("Guardar Consulta");
        Aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Aceptar.setEnabled(false);
        Aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AceptarActionPerformed(evt);
            }
        });
        Aceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                AceptarKeyPressed(evt);
            }
        });
        getContentPane().add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 90, 30));

        cve.setForeground(new java.awt.Color(102, 51, 0));
        cve.setCaretColor(new java.awt.Color(0, 0, 102));
        cve.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cveActionPerformed(evt);
            }
        });
        cve.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cveKeyTyped(evt);
            }
        });
        getContentPane().add(cve, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 130, -1));

        padAct.setColumns(20);
        padAct.setForeground(new java.awt.Color(102, 51, 0));
        padAct.setRows(5);
        padAct.setTabSize(6);
        padAct.setCaretColor(new java.awt.Color(0, 0, 102));
        padAct.setEnabled(false);
        padAct.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                padActKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                padActKeyTyped(evt);
            }
        });
        pada.setViewportView(padAct);

        getContentPane().add(pada, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 200, 250, 110));

        Cancelar.setBackground(new java.awt.Color(153, 153, 0));
        Cancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar.setText("Cancelar");
        Cancelar.setToolTipText("Cancelar Consulta");
        Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, -1, 30));

        jButton_Regresar2.setBackground(new java.awt.Color(153, 153, 0));
        jButton_Regresar2.setFont(new java.awt.Font("Zilla Slab Medium", 1, 14)); // NOI18N
        jButton_Regresar2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Regresar2.setText("<");
        jButton_Regresar2.setToolTipText("Regresar al Submenú de Alumnos");
        jButton_Regresar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_Regresar2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_Regresar2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Regresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 30));

        jLabel15.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 51, 0));
        jLabel15.setText("Fecha");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, 20));

        jLabel16.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 51, 0));
        jLabel16.setText("Antecedentes");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 100, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        jLabel17.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 51, 0));
        jLabel17.setText("CVE del Alumno");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 20));

        jLabel18.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 51, 0));
        jLabel18.setText("Plan de Tratamiento");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 150, 20));

        jLabel19.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 51, 0));
        jLabel19.setText("Padecimiento Actual");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 20));

        jLabel20.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 51, 0));
        jLabel20.setText("Medicamento");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 100, 20));

        jLabel2.setFont(new java.awt.Font("Zilla Slab SemiBold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Ingreso de Consulta de Alumno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel21.setBackground(new java.awt.Color(0, 102, 51));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.png"))); // NOI18N
        jLabel21.setText("jLabel5");
        jLabel21.setMaximumSize(new java.awt.Dimension(540, 100));
        jLabel21.setMinimumSize(new java.awt.Dimension(420, 80));
        jLabel21.setPreferredSize(new java.awt.Dimension(540, 100));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, 650, 110));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanco.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AceptarActionPerformed
    {//GEN-HEADEREND:event_AceptarActionPerformed
        try
        {
            HistorialClinico pcd = new HistorialClinico(padAct.getText(), antece.getText(), medic.getText(), planTrat.getText(), fecha);
            VtnPrincipal.h[vne] = Manipulacion.insCon(VtnPrincipal.h[vne], vne, pcd, this);//Funcion para insertar datos
            ManipulacionArchivos.guarda(this, VtnPrincipal.h, "Historial.dat");
            Mensajes.exito(this, "Datos guardados con éxito");
            CtrlInterfaz.limpia(cve, padAct, antece, medic, planTrat, fecha, vne, fechas);
            CtrlInterfaz.habilita(false, cve, padAct, antece, medic, planTrat, fecha, vne, fechas, Aceptar);
            CtrlInterfaz.cambia(cve);
        } catch (Exception e)
        {
            Mensajes.error(this, "Error: " + e.toString());
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void fechaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fechaKeyTyped
    {//GEN-HEADEREND:event_fechaKeyTyped

    }//GEN-LAST:event_fechaKeyTyped

    private void fechasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fechasKeyPressed
    {//GEN-HEADEREND:event_fechasKeyPressed

    }//GEN-LAST:event_fechasKeyPressed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fechaActionPerformed
    {//GEN-HEADEREND:event_fechaActionPerformed

    }//GEN-LAST:event_fechaActionPerformed

    private void medicKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_medicKeyTyped
    {//GEN-HEADEREND:event_medicKeyTyped
        Validaciones.validaAlfanumerico(evt, 700, medic.getText());
    }//GEN-LAST:event_medicKeyTyped

    private void medicKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_medicKeyPressed
    {//GEN-HEADEREND:event_medicKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, medic, planTrat);
    }//GEN-LAST:event_medicKeyPressed

    private void planTratKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_planTratKeyTyped
    {//GEN-HEADEREND:event_planTratKeyTyped
        Validaciones.validaAlfanumerico(evt, 700, planTrat.getText());
    }//GEN-LAST:event_planTratKeyTyped

    private void planTratKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_planTratKeyPressed
    {//GEN-HEADEREND:event_planTratKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, planTrat, Aceptar);
    }//GEN-LAST:event_planTratKeyPressed

    private void padActKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_padActKeyTyped
    {//GEN-HEADEREND:event_padActKeyTyped
        Validaciones.validaAlfabeticos(evt, 700, padAct.getText());
    }//GEN-LAST:event_padActKeyTyped

    private void padActKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_padActKeyPressed
    {//GEN-HEADEREND:event_padActKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, padAct, antece);
    }//GEN-LAST:event_padActKeyPressed

    private void anteceKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_anteceKeyTyped
    {//GEN-HEADEREND:event_anteceKeyTyped
        Validaciones.validaAlfanumerico(evt, 700, antece.getText());
    }//GEN-LAST:event_anteceKeyTyped

    private void anteceKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_anteceKeyPressed
    {//GEN-HEADEREND:event_anteceKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, antece, medic);
    }//GEN-LAST:event_anteceKeyPressed

    private void cveKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cveKeyTyped
    {//GEN-HEADEREND:event_cveKeyTyped
        Validaciones.validaEntero(evt, 7, cve.getText());
    }//GEN-LAST:event_cveKeyTyped

    private void cveKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cveKeyPressed
    {//GEN-HEADEREND:event_cveKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, cve, padAct);
    }//GEN-LAST:event_cveKeyPressed

    private void cveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cveActionPerformed
    {//GEN-HEADEREND:event_cveActionPerformed
        vne = Manipulacion.verificador(this, VtnPrincipal.d, 1, cve.getText());
        if (vne == -1)
        {
            Mensajes.error(this, "CVE no existente en registro, ingrese un CVE correcto");
            CtrlInterfaz.limpia(cve, fechas);
            CtrlInterfaz.habilita(false, cve, padAct);
            CtrlInterfaz.cambia(cve);
        }
        c = new GregorianCalendar();
        String d, m, a;
        d = Integer.toString(c.get(Calendar.DATE));
        m = Integer.toString(c.get(Calendar.MONTH));
        a = Integer.toString(c.get(Calendar.YEAR));
        int mm = Integer.parseInt(m);
        mm = mm + 1;
        String f = d + "/" + mm + "/" + a;
        fechas.setText(f);
        fecha = Validaciones.validaFecha(this, fechas.getText().length(), f, fecha, fechas);
    }//GEN-LAST:event_cveActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelarActionPerformed
    {//GEN-HEADEREND:event_CancelarActionPerformed
        CtrlInterfaz.limpia(cve, fechas, padAct, antece, medic, planTrat, Aceptar);
        CtrlInterfaz.habilita(false, cve, fechas, padAct, antece, medic, planTrat, Aceptar);
        CtrlInterfaz.habilita(false, Aceptar);
        CtrlInterfaz.cambia(cve);
    }//GEN-LAST:event_CancelarActionPerformed

    private void jButton_Regresar2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_Regresar2ActionPerformed
    {//GEN-HEADEREND:event_jButton_Regresar2ActionPerformed
        new VtnSubmenu().setVisible(true);
        VtnSubmenu.tsubmenu.setText("           Alumnos");
        dispose();
    }//GEN-LAST:event_jButton_Regresar2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        CtrlInterfaz.cambia(cve);
    }//GEN-LAST:event_formWindowOpened

    private void AceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_AceptarKeyPressed
    {//GEN-HEADEREND:event_AceptarKeyPressed
          try
        {
            HistorialClinico pcd = new HistorialClinico(padAct.getText(), antece.getText(), medic.getText(), planTrat.getText(), fecha);
            VtnPrincipal.h[vne] = Manipulacion.insCon(VtnPrincipal.h[vne], vne, pcd, this);//Funcion para insertar datos
            ManipulacionArchivos.guarda(this, VtnPrincipal.h, "Historial.dat");
            Mensajes.exito(this, "Datos guardados con éxito");
            CtrlInterfaz.limpia(cve, padAct, antece, medic, planTrat, fecha, vne, fechas);
            CtrlInterfaz.habilita(false, cve, padAct, antece, medic, planTrat, fecha, vne, fechas, Aceptar);
            CtrlInterfaz.cambia(cve);
        } catch (Exception e)
        {
            Mensajes.error(this, "Error: " + e.toString());
        }
    }//GEN-LAST:event_AceptarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnHCA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextArea antece;
    private javax.swing.JTextField cve;
    private javax.swing.JTextField fechas;
    private javax.swing.JButton jButton_Regresar2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea medic;
    private javax.swing.JTextArea padAct;
    private javax.swing.JScrollPane pada;
    private javax.swing.JTextArea planTrat;
    // End of variables declaration//GEN-END:variables
}
