/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author marip
 */
public class VtnPrincipal extends javax.swing.JFrame
{

    public static int opc;
    public static String mnu[] =//Guarda menu como un arreglo
    {
        "Alumnos", "Personal"
    };

    public static Datos d[];//Arreglo de datos
    public static int v = -1;
    public static HistorialClinico[][] h;

    public static void disablepaste(JComponent com)
    {
        com.getInputMap().put(KeyStroke.getKeyStroke("control V"), "none");
    }

    /**
     * Creates new form VtnReportes
     */
    public VtnPrincipal()
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * Metodo que hace posible ver el logo en la barra de tareas
     *
     * @return
     */
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Imagen1ORGlogo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        kuakoIMG = new javax.swing.JLabel();
        REGmedicos = new javax.swing.JLabel();
        salud = new javax.swing.JLabel();
        Personalbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        escudo = new javax.swing.JLabel();
        jButtonAlumnos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kuakoIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/kuako.png"))); // NOI18N
        kuakoIMG.setToolTipText("");
        getContentPane().add(kuakoIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 200, -1));

        REGmedicos.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        REGmedicos.setForeground(new java.awt.Color(102, 51, 0));
        REGmedicos.setText("REGISTROS MÉDICOS");
        getContentPane().add(REGmedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        salud.setFont(new java.awt.Font("Lato", 3, 14)); // NOI18N
        salud.setForeground(new java.awt.Color(255, 255, 255));
        salud.setText("En la UAEMéx nos preocupa tu bienestar");
        getContentPane().add(salud, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        Personalbutton.setBackground(new java.awt.Color(0, 102, 51));
        Personalbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Personalbutton.setForeground(new java.awt.Color(255, 255, 255));
        Personalbutton.setText("Personal");
        Personalbutton.setToolTipText("Submenú de Personal");
        Personalbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Personalbutton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PersonalbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Personalbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.setToolTipText("Cerrar programa");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 70, -1));

        escudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen1.png"))); // NOI18N
        getContentPane().add(escudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jButtonAlumnos.setBackground(new java.awt.Color(0, 102, 51));
        jButtonAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAlumnos.setText("Alumnos");
        jButtonAlumnos.setToolTipText("Submenú de Alumnos");
        jButtonAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAlumnos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAlumnosActionPerformed(evt);
            }
        });
        jButtonAlumnos.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jButtonAlumnosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jButtonAlumnosKeyTyped(evt);
            }
        });
        getContentPane().add(jButtonAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 102, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(540, 100));
        jLabel5.setMinimumSize(new java.awt.Dimension(420, 80));
        jLabel5.setPreferredSize(new java.awt.Dimension(540, 100));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 440, 660, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanco.jpg"))); // NOI18N
        Fondo.setText("jLabel1");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAlumnosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAlumnosActionPerformed
    {//GEN-HEADEREND:event_jButtonAlumnosActionPerformed
        opc = 1;
        new VtnSubmenu().setVisible(true);
        VtnSubmenu.tsubmenu.setText("           de Alumnos");
        dispose(); //cierra ventana automaticamente
    }//GEN-LAST:event_jButtonAlumnosActionPerformed

    private void PersonalbuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PersonalbuttonActionPerformed
    {//GEN-HEADEREND:event_PersonalbuttonActionPerformed
        opc = 2;
        new VtnSubmenu().setVisible(true);
        VtnSubmenu.tsubmenu.setText("           de Personal");
        dispose();
    }//GEN-LAST:event_PersonalbuttonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        d = (Datos[]) ManipulacionArchivos.cargaArr(this, ("Datos.dat"));
        h = (HistorialClinico[][]) ManipulacionArchivos.cargaMat(this, ("Historial.dat"));
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        ManipulacionArchivos.guardaA(this, d, "Datos.dat");
        ManipulacionArchivos.guarda(this, h, "Historial.dat");
    }//GEN-LAST:event_formWindowClosing

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jButton1KeyPressed
    {//GEN-HEADEREND:event_jButton1KeyPressed

    }//GEN-LAST:event_jButton1KeyPressed

    private void jButtonAlumnosKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jButtonAlumnosKeyPressed
    {//GEN-HEADEREND:event_jButtonAlumnosKeyPressed

    }//GEN-LAST:event_jButtonAlumnosKeyPressed

    private void jButtonAlumnosKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jButtonAlumnosKeyTyped
    {//GEN-HEADEREND:event_jButtonAlumnosKeyTyped

    }//GEN-LAST:event_jButtonAlumnosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Personalbutton;
    private javax.swing.JLabel REGmedicos;
    private javax.swing.JLabel escudo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAlumnos;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel kuakoIMG;
    private javax.swing.JLabel salud;
    // End of variables declaration//GEN-END:variables
}
